airline/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flights.urls")),
    path('users/', include("users.urls")),
]

flights/urls.py
from django.urls import path

from . import views

app_name = "flights"

urlpatterns = [
    path("", views.index,name = "index"), # name allows references uing {% url %}, views.index refenreces the function that will deal with this call
    path("<int:flight_id>", views.flightfunction, name = "Flight"), 
    path("<int:flight_id>/book", views.book, name = "book")
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name = "index"),
    path("login", views.login_view, name = "login"),
    path("logout", views.logout_view, name = "logout")
]

flights/models.py
from django.db import models

# Create your models here.

class airport(models.Model):
    code = models.CharField(max_length = 3)
    city = models.CharField(max_length = 64)

    def __str__(self):
        return f"{self.city} ({self.code})"

class flight(models.Model):
    origin = models.ForeignKey(airport, on_delete=models.CASCADE, related_name = "departures")
    destination = models.ForeignKey(airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id} : {self.origin} to {self.destination}"

    def is_valid_flight(self):
        return self.destination!=self.origin and self.duration>0

class passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(flight, blank = True, related_name="passengers") # ManyToManyField allows us to reference multiple flights to one passenger and vice versa # related name will act as a token that allows for this.

    def __str__(self):
        return f"{self.first} {self.last}"

users/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import * # urls imports views and views imports models. urls go to urls that views generate with data from models.

def index(request):
    return render(request,"flights/index.html",{
        "flights": flight.objects.all()
    })

def flightfunction(request, flight_id):
    Flight = flight.objects.get(pk=flight_id)
    return render(request, "flights/flight.html", {
        "Flight" : Flight,
        "passengers" : Flight.passengers.all(),
        "non_passengers" : passenger.objects.exclude(flights=Flight).all(),
    }) 

def book(request, flight_id):    
    if request.method == "POST":
        Flight = flight.objects.get(id=flight_id)
        Passenger = passenger.objects.get(id=int(request.POST["passenger"]))
        Passenger.flights.add(Flight)
        return HttpResponseRedirect(reverse("flights:Flight", args = (Flight.id,)))
    return HttpResponseRedirect(reverse("flights:index"))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def index(request):
    if not request.user.is_authenticated: # checks if the user has been logged in already or not. If not, we just go to the login page
        return HttpResponseRedirect(reverse("login"))
    return render(request, "users/user.html") # if the user is authenticated then we go to their page

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username = username, password = password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index")) # reverse utilized the name of the page to go to the url associated with it 
        else:
            return render(request,"users/login.html",{
                "message": "Invalid credentials"
            })

    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "logged out."
    })

flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}

    <h1> Flight {{Flight.id}}</h1>
    <ul>
        <li> Origin {{Flight.origin}} </li>
        <li> Destination {{Flight.destination}} </li>
        <li> Duration {{Flight.duration}} </li>
    </ul>

    <h2>Passengers</h2>

    <ul>
        {% for passenger in passengers %}
            <li> {{passenger}} </li>
        {% empty %}
            <li>No passengers</li> 
        {% endfor %}
    </ul>

    <h2> Add passenger </h2>

    <form action = "{% url 'flights:book' Flight.id %}" method = "post"> 
        {% csrf_token %}    
        <select name = "passenger">
            {% for passenger in non_passengers %}
                <option value = "{{ passenger.id }}"> {{ passenger }} </option>
            {% endfor %}
        </select>
        <input type = "submit">
    </form>

    <a href = "{%url 'flights:index' %}"> Back to Flights List</a>

{% endblock %}

flights/templates/flights/index.html
{% extends "flights/layout.html"%}

{% block body %}

<h1> Flights </h1>
<ul>
    {% for flight in flights %}
        <li> 
        <a href = "{% url 'flights:Flight' flight.id %}">
            Flight {{flight.id}}: {{flight.origin}} to {{flight.destination}}
        </a>
    </li> 
    {% endfor %}
</ul>

{% endblock %}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>flights</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}

    {% if message %}
        <div> {{message}} </div>
    {% endif %}
    <form action = "{% url 'users:login' %}" method="post"> 
        {% csrf_token %}
        <input type = "text" name = "username" placeholder = "Username">
        <input type = "password" name = "password" placeholder = "Password">
        <input type = "submit" value = "login">
    </form>
{% endblock %}

users/templates/users/user.html
{% extends "users/layout.html" %}

{% block body %}

    <h1> Welcome, {{ request.user.first_name }}</h1>

    <ul>
        <li> Username: {{request.user.username }} </li>
        <li> Email: {{ request.user.email }} </li>
    </ul>

    <a href = "{% url 'users:logout' %}"> Log me out, aaaah</a>
{% endblock %}